######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 23 19:19:01 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Request.h Window.h
SOURCES += main.cpp Request.cpp Window.cpp
